import pytest

from xerama.domain.enums import ProviderErrorKind
from xerama.providers.errors import ProviderError
from xerama.providers.fake_image import FakeImageProvider
from xerama.providers.health import ProviderHealthTracker
from xerama.providers.image import ImageGenerationRequest, ImageProviderCapabilities
from xerama.services.media_router import MediaProviderRouter, NoEligibleProviderError


def _always_compatible(provider) -> bool:
    return True


async def test_fake_provider_end_to_end_generation() -> None:
    provider = FakeImageProvider([b"generated bytes"], name="only")
    router = MediaProviderRouter([provider])
    request = ImageGenerationRequest(prompt="a shot")

    selected, data, attempts = await router.generate(
        _always_compatible, lambda p: p.generate(request, [])
    )

    assert selected is provider
    assert data == b"generated bytes"
    assert [a.outcome for a in attempts] == ["selected"]


async def test_deterministic_policy_ordering_prefers_higher_priority() -> None:
    low = FakeImageProvider([b"low"], capabilities=ImageProviderCapabilities(priority=0), name="low")
    high = FakeImageProvider([b"high"], capabilities=ImageProviderCapabilities(priority=10), name="high")
    router = MediaProviderRouter([low, high])
    request = ImageGenerationRequest(prompt="p")

    selected, data, attempts = await router.generate(
        _always_compatible, lambda p: p.generate(request, [])
    )

    assert selected is high
    assert data == b"high"
    assert attempts[0].provider_name == "high"


async def test_stable_tie_break_keeps_registration_order() -> None:
    first = FakeImageProvider(name="first", capabilities=ImageProviderCapabilities(priority=5))
    second = FakeImageProvider(name="second", capabilities=ImageProviderCapabilities(priority=5))
    router = MediaProviderRouter([first, second])
    assert [p.name for p in router.providers] == ["first", "second"]


async def test_capability_filtering_skips_incompatible_provider() -> None:
    incompatible = FakeImageProvider(
        [b"should not be used"],
        capabilities=ImageProviderCapabilities(priority=10),
        name="incompatible",
    )
    compatible = FakeImageProvider(
        [b"used"], capabilities=ImageProviderCapabilities(priority=0), name="compatible"
    )
    router = MediaProviderRouter([incompatible, compatible])
    request = ImageGenerationRequest(prompt="p")

    def is_compatible(provider) -> bool:
        return provider.name == "compatible"

    selected, data, attempts = await router.generate(is_compatible, lambda p: p.generate(request, []))

    assert selected is compatible
    assert data == b"used"
    assert incompatible.calls == []
    outcomes = {a.provider_name: a.outcome for a in attempts}
    assert outcomes["incompatible"] == "incompatible"
    assert outcomes["compatible"] == "selected"


async def test_raises_when_no_provider_is_compatible() -> None:
    provider = FakeImageProvider([b"unused"])
    router = MediaProviderRouter([provider])

    with pytest.raises(NoEligibleProviderError) as excinfo:
        await router.generate(lambda p: False, lambda p: p.generate(ImageGenerationRequest(prompt="p"), []))

    assert excinfo.value.attempts[0].outcome == "incompatible"
    assert provider.calls == []


async def test_health_circuit_skips_unhealthy_provider() -> None:
    unhealthy = FakeImageProvider([b"unused"], name="unhealthy")
    healthy = FakeImageProvider([b"used"], name="healthy")
    health = ProviderHealthTracker()
    health.record_failure("unhealthy", "default", ProviderErrorKind.AUTHENTICATION)  # trips breaker immediately
    router = MediaProviderRouter([unhealthy, healthy], health=health)
    request = ImageGenerationRequest(prompt="p")

    selected, data, attempts = await router.generate(
        _always_compatible, lambda p: p.generate(request, [])
    )

    assert selected is healthy
    assert unhealthy.calls == []
    outcomes = {a.provider_name: a.outcome for a in attempts}
    assert outcomes["unhealthy"] == "unhealthy"
    assert outcomes["healthy"] == "selected"


async def test_fallback_tries_next_provider_after_failure() -> None:
    failing = FakeImageProvider(
        [ProviderError(ProviderErrorKind.TIMEOUT, "boom")], name="failing"
    )
    backup = FakeImageProvider([b"backup result"], name="backup")
    health = ProviderHealthTracker()
    router = MediaProviderRouter([failing, backup], health=health)
    request = ImageGenerationRequest(prompt="p")

    selected, data, attempts = await router.generate(
        _always_compatible, lambda p: p.generate(request, [])
    )

    assert selected is backup
    assert data == b"backup result"
    assert len(failing.calls) == 1  # the failing provider WAS attempted, just failed
    outcomes = {a.provider_name: a.outcome for a in attempts}
    assert outcomes["failing"] == "failed"
    assert outcomes["backup"] == "selected"
    assert health.is_healthy("failing", "default") is True  # one timeout alone doesn't trip the breaker


async def test_raises_when_every_eligible_provider_fails() -> None:
    only = FakeImageProvider([ProviderError(ProviderErrorKind.TIMEOUT, "boom")], name="only")
    router = MediaProviderRouter([only])

    with pytest.raises(NoEligibleProviderError) as excinfo:
        await router.generate(
            _always_compatible, lambda p: p.generate(ImageGenerationRequest(prompt="p"), [])
        )

    assert excinfo.value.attempts[0].outcome == "failed"
    assert excinfo.value.attempts[0].detail == "boom"
