"""add shot blocking plan

Revision ID: 25a65ab303cb
Revises: 8fe8803fbf26
Create Date: 2026-08-25 04:33:12.125558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a65ab303cb'
down_revision: Union[str, Sequence[str], None] = '8fe8803fbf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('blocking_plan', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shots', 'blocking_plan')
    # ### end Alembic commands ###
