"""add season plans

Revision ID: 276af56e655b
Revises: 95469d134873
Create Date: 2026-08-25 00:46:34.837174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276af56e655b'
down_revision: Union[str, Sequence[str], None] = '95469d134873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('qc_status', sa.String(length=16), nullable=False),
    sa.Column('qc_score', sa.Float(), nullable=False),
    sa.Column('qc_reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_plans_series_id'), 'season_plans', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_plans_series_id'), table_name='season_plans')
    op.drop_table('season_plans')
    # ### end Alembic commands ###
