"""add character casting studio

Revision ID: 2baba9e0ec9a
Revises: 4e20f6801cd1
Create Date: 2026-08-25 03:37:33.085850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2baba9e0ec9a'
down_revision: Union[str, Sequence[str], None] = '4e20f6801cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_physical_state_variants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('reference_asset_ids', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_physical_state_variants_character_id'), 'character_physical_state_variants', ['character_id'], unique=False)
    op.create_table('character_wardrobe_variants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('reference_asset_ids', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_wardrobe_variants_character_id'), 'character_wardrobe_variants', ['character_id'], unique=False)
    op.add_column('assets', sa.Column('character_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_assets_character_id'), 'assets', ['character_id'], unique=False)
    op.add_column('characters', sa.Column('reference_pack', sa.JSON(), nullable=False))
    op.add_column('characters', sa.Column('identity_provenance', sa.JSON(), nullable=False))
    op.add_column('characters', sa.Column('locked', sa.Boolean(), nullable=False))
    op.add_column('characters', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'version')
    op.drop_column('characters', 'locked')
    op.drop_column('characters', 'identity_provenance')
    op.drop_column('characters', 'reference_pack')
    op.drop_index(op.f('ix_assets_character_id'), table_name='assets')
    op.drop_column('assets', 'character_id')
    op.drop_index(op.f('ix_character_wardrobe_variants_character_id'), table_name='character_wardrobe_variants')
    op.drop_table('character_wardrobe_variants')
    op.drop_index(op.f('ix_character_physical_state_variants_character_id'), table_name='character_physical_state_variants')
    op.drop_table('character_physical_state_variants')
    # ### end Alembic commands ###
