"""add runtime settings

Revision ID: 2ff021f9d88a
Revises: 885220810535
Create Date: 2026-08-27 22:35:05.616369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff021f9d88a'
down_revision: Union[str, Sequence[str], None] = '885220810535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('llm_provider', sa.String(length=16), nullable=False),
    sa.Column('ollama_model', sa.String(length=128), nullable=False),
    sa.Column('ollama_base_url', sa.String(length=255), nullable=False),
    sa.Column('media_provider', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_settings')
    # ### end Alembic commands ###
