"""add shot director fields

Revision ID: 42f264e2c041
Revises: a6445d655373
Create Date: 2026-08-25 01:12:30.183877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f264e2c041'
down_revision: Union[str, Sequence[str], None] = 'a6445d655373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('blocking', sa.Text(), nullable=False))
    op.add_column('shots', sa.Column('continuity_group', sa.String(length=64), nullable=True))
    op.add_column('shots', sa.Column('provider_requirements', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_shots_continuity_group'), 'shots', ['continuity_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shots_continuity_group'), table_name='shots')
    op.drop_column('shots', 'provider_requirements')
    op.drop_column('shots', 'continuity_group')
    op.drop_column('shots', 'blocking')
    # ### end Alembic commands ###
