"""add assets table

Revision ID: 4e20f6801cd1
Revises: 42f264e2c041
Create Date: 2026-08-25 01:19:59.488645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e20f6801cd1'
down_revision: Union[str, Sequence[str], None] = '42f264e2c041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=True),
    sa.Column('episode_id', sa.String(length=32), nullable=True),
    sa.Column('scene_number', sa.Integer(), nullable=True),
    sa.Column('shot_number', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('take_number', sa.Integer(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_content_hash'), 'assets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_assets_episode_id'), 'assets', ['episode_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_series_id'), 'assets', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_series_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_episode_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_content_hash'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
