"""add job queue fields

Revision ID: 516daeedc39b
Revises: 6b290db8e00b
Create Date: 2026-08-25 06:37:07.808953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516daeedc39b'
down_revision: Union[str, Sequence[str], None] = '6b290db8e00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted with server_default
    # values so this stays forward-compatible with a non-empty
    # generation_jobs table (existing rows get sane queue defaults instead
    # of the migration failing on the NOT NULL columns). ###
    op.add_column(
        'generation_jobs', sa.Column('priority', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'generation_jobs', sa.Column('payload', sa.JSON(), nullable=False, server_default='{}')
    )
    op.add_column('generation_jobs', sa.Column('depends_on_job_id', sa.String(length=32), nullable=True))
    # SQLite's ADD COLUMN rejects non-constant defaults (CURRENT_TIMESTAMP
    # included) outright - a fixed epoch literal is used instead so
    # existing rows get a valid, already-due `scheduled_at` (immediately
    # claimable) rather than blocking the migration.
    op.add_column(
        'generation_jobs',
        sa.Column(
            'scheduled_at', sa.DateTime(), nullable=False, server_default='1970-01-01 00:00:00'
        ),
    )
    op.add_column(
        'generation_jobs', sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='3')
    )
    op.add_column('generation_jobs', sa.Column('lease_owner', sa.String(length=64), nullable=True))
    op.add_column('generation_jobs', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_generation_jobs_priority'), 'generation_jobs', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_jobs_priority'), table_name='generation_jobs')
    op.drop_column('generation_jobs', 'lease_expires_at')
    op.drop_column('generation_jobs', 'lease_owner')
    op.drop_column('generation_jobs', 'max_attempts')
    op.drop_column('generation_jobs', 'scheduled_at')
    op.drop_column('generation_jobs', 'depends_on_job_id')
    op.drop_column('generation_jobs', 'payload')
    op.drop_column('generation_jobs', 'priority')
    # ### end Alembic commands ###
