"""add music and sound effect cues

Revision ID: 55a6461be3fa
Revises: d3f28dc36975
Create Date: 2026-08-25 05:49:02.751199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a6461be3fa'
down_revision: Union[str, Sequence[str], None] = 'd3f28dc36975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_cues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=128), nullable=False),
    sa.Column('mood', sa.String(length=128), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('ducking_db', sa.Float(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('rights', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_cues_episode_id'), 'music_cues', ['episode_id'], unique=False)
    op.create_table('sound_effect_cues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('gain_db', sa.Float(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('rights', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sound_effect_cues_episode_id'), 'sound_effect_cues', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sound_effect_cues_episode_id'), table_name='sound_effect_cues')
    op.drop_table('sound_effect_cues')
    op.drop_index(op.f('ix_music_cues_episode_id'), table_name='music_cues')
    op.drop_table('music_cues')
    # ### end Alembic commands ###
