"""add shot production priority

Revision ID: 6b290db8e00b
Revises: f82b2a45f05f
Create Date: 2026-08-25 06:07:12.412718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b290db8e00b'
down_revision: Union[str, Sequence[str], None] = 'f82b2a45f05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('production_priority', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shots', 'production_priority')
    # ### end Alembic commands ###
