"""add shot video productions

Revision ID: 8fe8803fbf26
Revises: c9737e7a2af4
Create Date: 2026-08-25 04:17:39.470136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe8803fbf26'
down_revision: Union[str, Sequence[str], None] = 'c9737e7a2af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shot_video_productions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('continuity_group', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_take_asset_id', sa.String(length=32), nullable=True),
    sa.Column('extracted_last_frame_asset_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shot_video_productions_continuity_group'), 'shot_video_productions', ['continuity_group'], unique=False)
    op.create_index(op.f('ix_shot_video_productions_episode_id'), 'shot_video_productions', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shot_video_productions_episode_id'), table_name='shot_video_productions')
    op.drop_index(op.f('ix_shot_video_productions_continuity_group'), table_name='shot_video_productions')
    op.drop_table('shot_video_productions')
    # ### end Alembic commands ###
