"""initial schema

Revision ID: 95469d134873
Revises: 
Create Date: 2026-08-24 23:04:22.021016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95469d134873'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=False),
    sa.Column('target_platform', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_candidates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('slot', sa.String(length=1), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=False),
    sa.Column('candidate', sa.JSON(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_candidates_batch_id'), 'concept_candidates', ['batch_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('result_asset_ids', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('approved_concept', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_decisions_batch_id'), 'judge_decisions', ['batch_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('logline', sa.Text(), nullable=False),
    sa.Column('genre', sa.JSON(), nullable=False),
    sa.Column('subgenres', sa.JSON(), nullable=False),
    sa.Column('tone', sa.JSON(), nullable=False),
    sa.Column('target_audience', sa.String(length=128), nullable=False),
    sa.Column('episode_count_target', sa.Integer(), nullable=False),
    sa.Column('episode_duration_target_seconds', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('age', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('fear', sa.Text(), nullable=False),
    sa.Column('flaw', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('character_dna', sa.JSON(), nullable=False),
    sa.Column('visual_identity_id', sa.String(length=64), nullable=True),
    sa.Column('voice_identity_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('opening_hook', sa.Text(), nullable=False),
    sa.Column('central_conflict', sa.Text(), nullable=False),
    sa.Column('turn', sa.Text(), nullable=False),
    sa.Column('reveal', sa.Text(), nullable=False),
    sa.Column('cliffhanger_type', sa.String(length=64), nullable=False),
    sa.Column('cliffhanger', sa.Text(), nullable=False),
    sa.Column('duration_target_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outline', sa.JSON(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('truth_status', sa.String(length=16), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('introduced_episode', sa.Integer(), nullable=True),
    sa.Column('planned_reveal_episode', sa.Integer(), nullable=True),
    sa.Column('actual_reveal_episode', sa.Integer(), nullable=True),
    sa.Column('knowledge', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_bibles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('central_dramatic_question', sa.Text(), nullable=False),
    sa.Column('protagonist_objective', sa.Text(), nullable=False),
    sa.Column('primary_opposition', sa.Text(), nullable=False),
    sa.Column('emotional_engine', sa.Text(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('world_rules', sa.JSON(), nullable=False),
    sa.Column('central_secret', sa.Text(), nullable=False),
    sa.Column('ending_target', sa.Text(), nullable=False),
    sa.Column('prohibited_contradictions', sa.JSON(), nullable=False),
    sa.Column('locked_facts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id')
    )
    op.create_table('episode_state_changes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('committed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('gate', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('repair_recommendation', sa.Text(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('source_character_id', sa.String(length=64), nullable=False),
    sa.Column('target_character_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('public_status', sa.String(length=128), nullable=False),
    sa.Column('private_status', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Float(), nullable=False),
    sa.Column('romantic_state', sa.String(length=64), nullable=False),
    sa.Column('valid_from_episode', sa.Integer(), nullable=False),
    sa.Column('valid_to_episode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['source_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('time_of_day', sa.String(length=32), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('conflict', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('character_ids', sa.JSON(), nullable=False),
    sa.Column('narrative_function', sa.String(length=128), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('camera', sa.JSON(), nullable=False),
    sa.Column('visual', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('micro_beats', sa.JSON(), nullable=False),
    sa.Column('audio_mode', sa.String(length=16), nullable=False),
    sa.Column('continuity_requirements', sa.JSON(), nullable=False),
    sa.Column('generation_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shots')
    op.drop_table('scenes')
    op.drop_table('relationships')
    op.drop_table('quality_reports')
    op.drop_table('episode_state_changes')
    op.drop_table('series_bibles')
    op.drop_table('knowledge_facts')
    op.drop_table('episodes')
    op.drop_table('characters')
    op.drop_table('series')
    op.drop_index(op.f('ix_judge_decisions_batch_id'), table_name='judge_decisions')
    op.drop_table('judge_decisions')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_concept_candidates_batch_id'), table_name='concept_candidates')
    op.drop_table('concept_candidates')
    op.drop_table('projects')
    # ### end Alembic commands ###
