"""add style bible and storyboards

Revision ID: c9737e7a2af4
Revises: 2baba9e0ec9a
Create Date: 2026-08-25 03:48:09.430068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9737e7a2af4'
down_revision: Union[str, Sequence[str], None] = '2baba9e0ec9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_bibles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('style_asset_id', sa.String(length=32), nullable=True),
    sa.Column('style_dna', sa.Text(), nullable=False),
    sa.Column('palette', sa.JSON(), nullable=False),
    sa.Column('lighting', sa.String(length=255), nullable=False),
    sa.Column('texture', sa.String(length=255), nullable=False),
    sa.Column('color_temperature', sa.String(length=255), nullable=False),
    sa.Column('composition_rules', sa.JSON(), nullable=False),
    sa.Column('negatives', sa.JSON(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_bibles_series_id'), 'style_bibles', ['series_id'], unique=True)
    op.create_table('storyboards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('layout_description', sa.Text(), nullable=False),
    sa.Column('approved_keyframe_asset_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboards_episode_id'), 'storyboards', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storyboards_episode_id'), table_name='storyboards')
    op.drop_table('storyboards')
    op.drop_index(op.f('ix_style_bibles_series_id'), table_name='style_bibles')
    op.drop_table('style_bibles')
    # ### end Alembic commands ###
