"""add chat_model to runtime settings

Revision ID: df85e57bd33b
Revises: 2ff021f9d88a
Create Date: 2026-08-27 23:56:18.527156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df85e57bd33b'
down_revision: Union[str, Sequence[str], None] = '2ff021f9d88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'runtime_settings',
        sa.Column(
            'chat_model', sa.String(length=128), nullable=False,
            server_default='anthropic/claude-sonnet-5',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtime_settings', 'chat_model')
    # ### end Alembic commands ###
