"""add subtitle cues

Revision ID: f82b2a45f05f
Revises: 55a6461be3fa
Create Date: 2026-08-25 05:58:54.487698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82b2a45f05f'
down_revision: Union[str, Sequence[str], None] = '55a6461be3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitle_cues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitle_cues_episode_id'), 'subtitle_cues', ['episode_id'], unique=False)
    op.create_index(op.f('ix_subtitle_cues_language'), 'subtitle_cues', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtitle_cues_language'), table_name='subtitle_cues')
    op.drop_index(op.f('ix_subtitle_cues_episode_id'), table_name='subtitle_cues')
    op.drop_table('subtitle_cues')
    # ### end Alembic commands ###
